name: docs

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [main]
  # 手动触发部署
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup Yarn
        # You may pin to the exact commit or the version.
        # uses: mskelton/setup-yarn@2fd0f48147cbee4fd8a71723a3b86851d86ba46b
        uses: mskelton/setup-yarn@v1.4.0
        with:
          # Additional flags to pass to the install command.
          #flags: # optional
          # Node version to use, defaults to the current LTS version.
          node-version: 18
          # Git ref to checkout. Passed to `actions/checkout`.
          #ref: # optional
          # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm
          cache: yarn

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # 选择要使用的 node 版本
          node-version: 18
          # 缓存 yarn 依赖
          cache: yarn

      # 运行构建脚本
      - name: Build VuePress site
        run: yarn docs:build

      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          # 部署到 main 分支
          target_branch: main
          # 部署目录为 VuePress 的默认输出目录
          build_dir: docs/docs/.vuepress/dist
        env:
          # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
